### ISSUE TITLE
Usage instructions can leak secrets to logs

### ISSUE THREAD

**Issue by cpswan** [espebra/filebin2#11]
If I mess up a command line argument then the app very helpfully prints out usage instructions:

```
Usage of /usr/local/bin/filebin2:
app_1  |   -access-log string
app_1  |        Path for access.log output (default "/var/log/filebin/access.log")
app_1  |   -admin-password string
app_1  |        Admin password (default "changeme")
app_1  |   -admin-username string
app_1  |        Admin username (default "admin")
...
```

But the defaults printed out include information from correctly set environment variables, including secrets:

```
...
app_1  |   -s3-secret-key string
app_1  |        S3 secret key (default "Xt5F9x9UimLZNxtB4Zoo54TMTdjp85yZp3r2s59H")
...
```

**Comment by espebra** [comment]
I agree, this is the opposite of great. I'll see if I can come up with a fix for it, perhaps I'll just remove the flags that allow passwords to be specified on the command line.

Thank you for reporting.
