### ISSUE TITLE
Any new features ideas

### ISSUE THREAD

**Issue by AbdullahAki** [espebra/filebin2#17]
Hello there,

I loved this project and I would like to contribute. What features can I make?

**Comment by espebra** [comment]
I'm glad you like it and thanks for the offer to contribute. I don't have a list of future features ready, but I'll see if I can write up a list of potential future features in the README file. From the top of my head, though, one of the next things that need to be addressed is some feature to help limit abuse. In the earlier version of filebin I added a short lived token, but I'd like to avoid this if possible. Some person also requested the opportunity to resume uploads also, and I haven't looked into what would be required to get this to work.

**Comment by AbdullahAki** [comment]
I did some research on "resume uploads" too. I've read a few articles. If you want, I can try something on this subject.

**Comment by espebra** [comment]
Feel free to try to do something on this subject, it would be interesting to see what needs to change for it to work properly. As I wrote previously I haven't given this much thought myself, so I'm not sure the complexity or amount of work needed. It may be a challenging first feature to contribute, but it is a good one and if you're up for it then go ahead. Feel free to share ideas and plans if you want to feedback along the way. A draft PR may be a good idea.

**Comment by espebra** [comment]
I'm closing this for now.
