### ISSUE TITLE
Is storage full?

### ISSUE THREAD

**Issue by datawookie** [espebra/filebin2#19]
Hi!

It looks like the storage might be full. Is it possible to clear up some files or allocate more storage?

Thanks, Andrew.

![image](https://user-images.githubusercontent.com/6134409/142174216-c7b0072b-6f51-42ec-94b3-4c46d84ca2df.png)

**Comment by espebra** [comment]
Hi Andrew,

Files are expired automatically or deleted manually (those knowing the URL to a bin can delete it), and when it happens storage is freed and new files can be uploaded. This is a continuous process. The hosting of filebin.net is generously provided for free by my [previous employer](https://www.redpill-linpro.com/) and there is a limit to how much capacity that can be offered. Keep in mind that it's a free service, not ad supported or anything.

If the storage capacity is reached it usually takes a few hours until new files can be uploaded. If you need more storage capacity or guaranteed capacity you can consider self hosting your own instance.

**Comment by datawookie** [comment]
Hi @espebra, I totally understand the situation. Was just bringing it to your attention in case there was intervention required. What was not clear to me from the warning message though was whether it was a problem that was specific to me (I had exhausted _my_ storage space) or global (to all users). Thanks, Andrew.

**Comment by datawookie** [comment]
Hi @espebra,

> If you need more storage capacity or guaranteed capacity you can consider self hosting your own instance.

I'm following your advice and setting up my own Filebin instance. It's very useful having the Docker Compose configuration readily available in the repository. :+1: However, I'm not clear about the S3 setup and what environment variables I need to provide (versus the ones that can be left at their default values).

Do you have instructions anywhere for getting this set up?

Thanks, Andrew.

**Comment by espebra** [comment]
Hi Andrew,

The documentation is severely lacking still unfortunately (A PR will be appreciated if you want to contribute). The environment variables I use for the database and S3 access are:

```
DATABASE_NAME=
DATABASE_USERNAME=
DATABASE_HOST=
DATABASE_PASSWORD=
S3_ENDPOINT= # hostname only
S3_REGION=
S3_BUCKET = # name of the bucket only, a single string without dots.
S3_ACCESS_KEY=
S3_SECRET_KEY=
```

If you want more debug information in the logs you can add the the `--s3-trace` command line parameter. This will tell filebin to log the request- and response headers that are related to S3, which could indicate what the problem is.

Note that I saw someone having problems with Filebin2 on Google Cloud Platform's S3 compatible object storage. I didn't explore this issue further.

**Comment by datawookie** [comment]
Hi @espebra, I've tried setting this up to the best of my ability but still not got it quite right. Have an S3 bucket, have assigned reasonable values to those environment variables but still no luck. Would you be able to have a 15 minute call with me (at your convenience) to iron out these niggles? Then I'll happily write up the documentation and PR. Thanks, Andrew.
