### ISSUE TITLE
Set filebin2 app hosting adresse

### ISSUE THREAD

**Issue by Nenuial** [espebra/filebin2#22]
I was able to setup the filebin app using my own docker instance. I am however running into a bit of an issue:
the filebin instance "believes" it is hosted at `filebin.net` (for QR codes for example).

Is there some way to set the app's hosting address (ideally as an environment variable in the docker-compose.yml)?

**Comment by espebra** [comment]
There is a parameter to filebin that is used to set the baseurl. It shows up if you do `filebin --help` but it is not yet documented here in the README.

> 
>   -baseurl string
>     	The base URL to use. Required for self-hosted instances. (default "https://filebin.net")

Can you try this and see if it solves the problem?

**Comment by Nenuial** [comment]
Thanks for the point!! Works fine.
