### ISSUE TITLE
Not an issue but some thanks ... Filebin2 is behind @mospherePro

### ISSUE THREAD

**Issue by cconstab** [espebra/filebin2#24]
@espebra ,

 A few months ago I got Filebin2 on K8S up and working and a few months later @cpswan also contributed (Chris and I work at atsign.com). Just wanted to let you know that our application @mospherePro is now up and running and is also opensource.
 
 https://github.com/atsign-foundation/atmosphere_pro

And it's also in the App/Play stores plus its coming soon to Mac/Windows.
 
 @mospherePro uses our instance Filebin2 on k8s as ephemeral storage of encrypted files.
 
 This app is not only a useful app but also a proof point for the opensource platform we have been building. 
 
 https://github.com/atsign-foundation
 
 So why am I reaching out ? We are puling together a story/article that describes the @mospherePro journey and wondered if you would like/would mind to be included in that write up?

Thanks so much for Filebin2!

@cconstab

**Comment by espebra** [comment]
Hi @cconstab 

Congratulations on launching your service! 🚀

It is fine if you want to include filebin in your article, I'm glad it can be useful.
