### ISSUE TITLE
Getting “You are blocked from using this service“ error

### ISSUE THREAD

**Issue by tie** [espebra/filebin2#27]
Hi! I’m not sure if this is the right place to report this issue, but I’m getting “You are blocked from using this service“ error whenever I open https://filebin.net in my web browser, independent of browser implementation (Safari/Firefox/Chrome), ISP (I’ve tried connecting from two different ISPs) and whether I enable [Cloudflare WARP](https://cloudflarewarp.com/) (or “VPN” in a layman’s terms). It’s possible to archive the front page (see https://archive.ph/QhYIR), so I guess it’s still accessible?

I’m not sure what’s the issue here since I don’t think I have abused the service (I’ve been only using it to share files between friends and occasionally as a workaround to transfer files from VM to host OS), and doesn’t look like a subnet ban to me too as I can’t access filebin with Cloudflare WARP.

If that would help with debugging, I’m currently leasing the following IP addresses from my primary ISP via DHCP:
- IPv4 95.84.246.62
- IPv6 subnet 2a02:2168:8fec:f600::/56
Both are dynamically assigned, but are reasonably static given no power outages.

**Comment by espebra** [comment]
IP addresses originating from Russia are currently blocked.

**Comment by megapro17** [comment]
For what reason?

**Comment by sergeevabc** [comment]
@tie, a few times in recent months I have encountered the equivalent of "no Jews allowed" signs of Nazi Germany. But today they are trying to discriminate against people from Russia. Well, xenophobia under the pretext of struggle between light and darkness is not a new phenomenon, centuries-old actually. Curiously, tech giants such as Github, where we are now, don't limit anything. And even in the homeland of the owner of this repository, I speak of Oslo, where the Vivaldi browser is developed, Russians can easily download it. Fortunately, there are other places to share files — take ([oshi.at](https://oshi.at/), for example. Cheer up!

**Comment by megapro17** [comment]
Garbage service

**Comment by aJ2d2O8I** [comment]
Someone needs to fork Filebin without that crappy country-restriction.
