### ISSUE TITLE
.apk file format not detecting 

### ISSUE THREAD

**Issue by gametrainee** [espebra/filebin2#30]
When I download apk its save as ZIP file

**Comment by espebra** [comment]
Can you please provide an `.apk` file that can be used for testing purposes?

Adding reference to https://github.com/gabriel-vasile/mimetype/issues/345

**Comment by gametrainee** [comment]
https://drive.google.com/file/d/0BzqCkyfL5GL5cDBXdUpIZU9Yd3M/view?usp=share_link&resourcekey=0-3RgroWkkSzmhM3_mYKlUEw

**Comment by espebra** [comment]
I confirm that the content-type detected for this file is `application/zip`, which is correct as far as I can tell. The apk file is a regular zip file with a certain file and folder structure inside, and the filename extension `.apk`. It doesn't change the fact that its correct content-type is `application/zip`, though.

The `content-disposition` header tells the user agent that the filename is (and should be) `Epic_Roll.apk` which is about as far as the server side can go to indicate the correct extension for the user agent. If the user agent (browser for example) decides to append a `.zip` extension in an attempt to be helpful then that is unfortunate for your use case.

At the moment I don't think there is anything that can or should be done in filebin to improve the situation, but please reopen if you have good input or ideas.
