### ISSUE TITLE
Is there a binary ?

### ISSUE THREAD

**Issue by amarc** [espebra/filebin2#31]
Hello, 

is there filebin Go binary that I can use to run it without Docker ? I would prefer to have this and all dependencies installed manually instead using Docker.

A.

**Comment by espebra** [comment]
There is currently no binary release available. However, the following commands should give you a Linux binary in `artifacts/filebin2-linux-amd64`, if you have golang and git installed:

```
git clone https://github.com/espebra/filebin2
cd filebin2
make linux
```
