### ISSUE TITLE
filebin on web server

### ISSUE THREAD

**Issue by Blisk** [espebra/filebin2#37]
Works this only on docker or I can use it on apache web server also?

**Comment by espebra** [comment]
It does not require docker. Filebin is a Go application with a built-in web server, which means that you can run it completely standalone if you want to. I guess you can put it behind apache with mod_proxy, but I haven't tried it myself.

**Comment by Blisk** [comment]
ok thank you.
Don't know how apache read go files, as far as I know it read php or html.
So I really don't know hot to setup this to work.

**Comment by espebra** [comment]
Apache can't read go files, but go files can be compiled to a static binary that you can execute as a program and run as a daemon.

The documentation is a bit lacking, but the steps should be:

1. Install go from https://go.dev/dl/ or from the operating system repositories.
2. git clone https://github.com/espebra/filebin2/
3. cd filebin2
4. make linux

This should put a binary in the filebin2/artifacts/ folder that you can execute.

**Comment by Blisk** [comment]
thank you I will try.
