### ISSUE TITLE
www.filebin.net not working due to an SSL error

### ISSUE THREAD

**Issue by otakuu** [espebra/filebin2#43]
<img width="498" alt="image" src="https://github.com/espebra/filebin2/assets/5182070/bf87c137-ae72-4694-b425-088fb5493ac7">

```
curl https://filebin.net
curl: (35) LibreSSL SSL_connect: SSL_ERROR_ZERO_RETURN in connection to filebin.net:443
```

Thx for fixing. Love your service!

**Comment by espebra** [comment]
Which curl version and operating system (and version) do you use here? I don't get any errors with my version of curl or OpenSSL.

**Comment by otakuu** [comment]
It also doesn't work on chrome for me:
<img width="1087" alt="image" src="https://github.com/espebra/filebin2/assets/5182070/9b4a27f0-2568-4176-af24-0d9ae11b59b6">

**Comment by otakuu** [comment]
It also doesn't work for chrome for me:
<img width="1087" alt="image" src="https://github.com/espebra/filebin2/assets/5182070/ab4faeda-f7b7-4bc8-b86f-f619c34c0d7f">

**Comment by otakuu** [comment]
It is working now...
