### ISSUE TITLE
Cancel missing.

### ISSUE THREAD

**Issue by joe-oli** [espebra/filebin2#52]
Thanks for the service at https://filebin.net/about
It works, however the basic feature to CANCEL once an upload has started is missing.

It was not clear to me if just closing the particular tab would stop the upload - but if it does, why not put some basic instructions or notice on the page to say so...

**Comment by espebra** [comment]
Closing the tab (or navigating away to another page) will indeed cancel the upload. It makes sense to put this in writing on the page, I'll get that sorted.
