### ISSUE TITLE
Not working due to SSL error

### ISSUE THREAD

**Issue by ubionexd** [espebra/filebin2#64]
![image](https://github.com/espebra/filebin2/assets/70473378/578c45c6-94e4-4b36-8b5e-5214b8658149)
Not just a problem on Firefox, cannot use with other apps/programs/services that depend on a valid SSL certificate.

**Comment by ubionexd** [comment]
It happens on my Windows 11 23H2 PC and my Raspberry Pi 4 running Raspberry Pi OS (or whatever its name is), which is based on Debian 12, and is fully up to date.

**Comment by espebra** [comment]
This is strange. I have verified that it works just fine on Windows 11 23H2 (latest) with Edge 124.0.2478.51 (latest) and Firefox 125.0.1 (latest). Filebin.net is using a Let's Encrypt certificate, which requires a root certificate called "ISRG Root X1" to be in your trust store. This root certificate is supposed to be there by default, but it would be great if you can verify.

Steps to verify:
1. In the search box in the Windows menu, run `certmgr.msc`
2. In the box that appears, go to "Trusted Root Certification Authorities"
3. Expand "Certificates".
4. Scroll down in the list of certificates and see if you can spot "ISRG Root X1" there.

**Comment by ubionexd** [comment]
I figured it out. It was my DNS provider's blocklist trying to display a "Warning, dangerous site!" message. Switched DNS, works fine now. Sorry for bothering you.
