### ISSUE TITLE
A couple of issues 

### ISSUE THREAD

**Issue by cconstab** [espebra/filebin2#8]
Not going too deep down the rabbit hole as yet. But I do see files in the AWS S3 bucket (yay!). 

But I have this odd issue that every time I upload a file in the browser UI it also downloads a <URL extension>.gz file Not sure why ??

The save URL link on the home page also downloads a .gz file 

A few errors in the log file as well for good measure.. Looks like some error in the template which I think is something else, I think the real issue I am seeing is the gorrilla/handlers but maybe they are linked..

Any how thought I would share todays findings/progress..

cconstab@cally:~/filebin2$ go build -mod=vendor
cconstab@cally:~/filebin2$ cp ../filebin2.old/env.sh ./
cconstab@cally:~/filebin2$ source env.sh
cconstab@cally:~/filebin2$ ./filebin2   -access-log ./logs --listen-host 0.0.0.0  -baseurl "http://192.168.1.149:8080"
Established session to S3AO at s3.us-west-1.amazonaws.com
Found S3AO bucket: filebin2-test
Starting Lurker process (interval: 5m0s)
Expiration: 168h0m0s
Starting HTTP server on 0.0.0.0:8080
Uploaded filename tent.jpg (582 kB) to bin gh5ha0767xby8095 (db in 0.008s, buffered in 0.016s, checksum in 0.005s, stored in 6.718s, total 6.746s)
Failed to execute template: template: :451:38: executing "bin" at <ne .CreatedAt .UpdatedAt>: error calling ne: invalid type for comparison
2021/02/16 01:00:43 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.(*responseLogger).WriteHeader (handlers.go:65)

**Comment by espebra** [comment]
This is probably related to some recent changes that were half baked before they were committed. I have pushed some updates now that should fix this. Can you retry?

The `docker-compose.yml` file now starts filebin by the way. I'd think that the easiest way to test out multi instance environment is to add more app containers to the compose file. I haven't done this.

**Comment by cconstab** [comment]
For sure and thanks!

**Comment by cconstab** [comment]
Well great news,, everything I have tested thus far is working well. During the week I will run up some Kubernetes yaml files and test  with X number of apps running and let you know how things go...
I will also migrate to my AWS S3 bucket and see how that goes.. 

Once I have the k8s files built and tested along with a READ.ME, I will create a pull request for you, if you want to include them..

This really is great work and thanks again for working on filebin2 !

**Comment by espebra** [comment]
Thank you for the feedback! A PR will be much appreciated. I'm closing this now as the issues reported were sorted.

**Comment by datawookie** [comment]
Hi @cconstab,

It looks like you have managed to get Filebin up and running with the S3 backend. Nice! :+1: 

I was wondering if you could maybe give me some advice. I have created an S3 bucket and then set up the following environment variables prior to doing `docker-compose up`:

```
export S3_ACCESS_KEY=
export S3_SECRET_KEY=
export S3_REGION=
export S3_BUCKET=
```

The `S3_BUCKET` is simply the name of the bucket, not an URL.

However with this setup I'm not getting files being uploaded to S3. Do you have any suggestions where I might have gone wrong? Did you by any chance document the process for setting this up?

Best regards, Andrew.
