### ISSUE TITLE
Please show when rate-limiting/ban will expire

### ISSUE THREAD

**Issue by otakuu** [espebra/filebin2#86]
I really love your service and I use it often. But sadly I got ratelimited (429, please slow down). That you need such a mechanism I totally understand. 

For a user that uses the service and not abuses it, it would be nice to see, when the ban expires. Like:` Please slow down. Your ban expires at 2024-11-18T13:37:42+00:00`

Thank you for considering this.

**Comment by espebra** [comment]
Ho otakuu,

I've bumped the limits, so hopefully you'll not be rate limited as often as before. I've also added information on how long until the block is lifted, if the rate limit is hit.

**Comment by otakuu** [comment]
Great news, thank you so much.
