### ISSUE TITLE
Read/write HTTP timeouts not configurable

### ISSUE THREAD

**Issue by zotanmew** [espebra/filebin2#88]
https://github.com/espebra/filebin2/blob/17df531afda06134857f1646a77d0e63fed2fefc/http.go#L214

It would be nice if this was configurable, as currently uploading large files over a slow connection results in errrors like

`Errno 125: "File upload of file \"<snip>.tar\" bin \"<snip>\" aborted at 15 GB of 29 GB, upload started 59 minutes ago: read tcp 127.0.0.1:61836->127.0.0.1:37790: i/o timeout (/tmp/filebin<snip>)"`

**Comment by espebra** [comment]
These should definitely be configurable.

**Comment by espebra** [comment]
Fixed now. I also bumped the read timeout to two hours on https://filebin.net/.
